server:
  port: 8010


spring:
  application:
    name: microservice-simple-consumer-movie

management:
  security:
    enabled: false

user:
  userServiceUrl: http://localhost:8000/


info:
  app: @project.artifactId@
  encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@


microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true


