server:
  port: 8010


spring:
  application:
    name: microservice-simple-consumer-movie

management:
  security:
    enabled: false

user:
  userServiceUrl: http://localhost:8000/


info:
  app: @project.artifactId@
  encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@


eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#    config:
#      feignName:
#        #相当于Request.Options
#        connectTimeout: 5000
#        #相当于Request.Options
#        readTimeout: 5000
#        #配置Feign的日志级别,相当于代码配置方式钟的Logger
#        loggerLevel: full
#
#        #feign的错误解码器,相当于代码配种方式中的ErrorDecoder
#        errorDecoder: com.example.SimpleErrorDecoder
#        #配置重试,相当于代码配置方式中的Retryer
#        retryer: com.example.SimpleRetryer
#
#        #配置拦截器,相当于代码配置方式中的RequestIntercepter
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false


#全局配置

