server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka


spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 20000Mb
      max-request-size: 25000Mb

