server:
  port: 8010


spring:
  application:
    name: microservice-simple-consumer-movie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

management:
  security:
    enabled: false

user:
  userServiceUrl: http://localhost:8000/


info:
  app: microservice-consumer-movie-ribbon-hystrix-turbine-mq
  encoding: UTF-8
  java:
    source: 1.8.0_162
    target: 1.8.0_162


eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true


