server:
  port: 8010


spring:
  application:
    name: microservice-simple-consumer-movie

management:
  security:
    enabled: false

user:
  userServiceUrl: http://localhost:8000/


info:
  app: microservice-simple-consumer-movie-metadata
  encoding: UTF-8
  java:
    source: 1.8.0_152-release
    target: 1.8.0_152-release



eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true


