server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

